// src/mockData.ts
import type { JobDescription } from './types';

// ─── JD Library ───────────────────────────────────────────────────────────────
// applicationCount is the single source of truth.
// The candidateStore will generate exactly this many role-appropriate candidates.

export const jdLibraryBase: JobDescription[] = [
    {
        id: 'jd1',
        title: 'Senior Full-Stack Engineer',
        department: 'Engineering',
        location: 'Remote / Bangalore',
        experienceMin: 4,
        experienceMax: 8,
        description: `We're looking for a Senior Full-Stack Engineer to join our product team. You'll work on mission-critical features, lead technical architecture decisions, and mentor junior engineers.\n\nYou'll be embedded in a cross-functional team and collaborate closely with Product, Design, and Data.`,
        mustHaveSkills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
        niceToHave: ['GraphQL', 'AWS', 'Redis', 'Docker', 'System Design'],
        status: 'Screening in Progress',
        createdAt: '2026-02-07T10:00:00Z',
        applicationCount: 214,
        strongCount: 0, // Computed dynamically in App.tsx after store builds
        shortlistedCount: 12,
        daysOpen: 20,
    },
    {
        id: 'jd2',
        title: 'Product Manager – Fintech',
        department: 'Product',
        location: 'Bangalore',
        experienceMin: 5,
        experienceMax: 10,
        description: 'Drive the roadmap for our core payment products. Work with engineering to define requirements and deliver high-impact features.',
        mustHaveSkills: ['Product Strategy', 'User Research', 'SQL', 'Fintech Experience'],
        niceToHave: ['MBA', 'Analytics', 'Agile'],
        status: 'Live – Accepting Applications',
        createdAt: '2026-02-10T09:00:00Z',
        applicationCount: 87,
        strongCount: 0,
        shortlistedCount: 0,
        daysOpen: 17,
    },
    {
        id: 'jd3',
        title: 'Backend Lead (Node.js)',
        department: 'Engineering',
        location: 'Remote',
        experienceMin: 7,
        experienceMax: 12,
        description: 'Lead the backend architecture for our scalable cloud systems. Ensure high performance and reliability.',
        mustHaveSkills: ['Node.js', 'PostgreSQL', 'Redis', 'System Design', 'Cloud Architecture'],
        niceToHave: ['Kubernetes', 'Go', 'Python'],
        status: 'Offer Closed',
        createdAt: '2026-01-12T14:00:00Z',
        applicationCount: 143,
        strongCount: 0,
        shortlistedCount: 5,
        daysOpen: 38,
    },
    {
        id: 'jd4',
        title: 'Frontend Engineer (React)',
        department: 'Engineering',
        location: 'Mumbai',
        experienceMin: 3,
        experienceMax: 6,
        description: 'Build beautiful and interactive user interfaces for our customer portal.',
        mustHaveSkills: ['React', 'TypeScript', 'Tailwind CSS', 'Redux'],
        niceToHave: ['Next.js', 'Testing Library', 'Figma'],
        status: 'Live – Accepting Applications',
        createdAt: '2026-02-25T11:30:00Z',
        applicationCount: 0,
        strongCount: 0,
        shortlistedCount: 0,
        daysOpen: 2,
    },
    {
        id: 'jd5',
        title: 'Data Analyst – Growth',
        department: 'Analytics',
        location: 'Hyderabad',
        experienceMin: 2,
        experienceMax: 5,
        description: 'Work with cross-functional teams to generate insights from product and marketing data.',
        mustHaveSkills: ['SQL', 'Python', 'Tableau', 'Statistics'],
        niceToHave: ['dbt', 'BigQuery', 'Looker'],
        status: 'Interview',
        createdAt: '2026-01-28T10:00:00Z',
        applicationCount: 96,
        strongCount: 0,
        shortlistedCount: 6,
        daysOpen: 30,
    },
    {
        id: 'jd6',
        title: 'DevOps Engineer',
        department: 'Infrastructure',
        location: 'Remote',
        experienceMin: 4,
        experienceMax: 8,
        description: 'Manage CI/CD pipelines, Kubernetes infrastructure, and cloud observability tooling.',
        mustHaveSkills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD'],
        niceToHave: ['Go', 'Prometheus', 'Grafana'],
        status: 'Offer Extended',
        createdAt: '2026-01-20T09:00:00Z',
        applicationCount: 61,
        strongCount: 0,
        shortlistedCount: 3,
        daysOpen: 37,
    },
];
