// src/mockData.ts
import type { JobDescription } from './types';

// ─── JD Library ───────────────────────────────────────────────────────────────
// applicationCount is the single source of truth.
// The candidateStore will generate exactly this many role-appropriate candidates.

export const jdLibraryBase: JobDescription[] = [
    {
        id: 'jd1',
        title: 'Senior Full-Stack Engineer',
        department: 'Engineering',
        location: 'Remote / Bangalore',
        experienceMin: 4,
        experienceMax: 8,
        description: `We're looking for a Senior Full-Stack Engineer to join our product engineering team. You'll architect and ship customer-facing features across our React frontend and Node.js/PostgreSQL backend, lead code reviews, and mentor junior engineers.\n\nYou'll be embedded in a cross-functional squad collaborating daily with Product, Design, and Data to solve complex scalability challenges in a high-growth environment.`,
        mustHaveSkills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
        niceToHave: ['GraphQL', 'AWS', 'Redis', 'Docker', 'System Design'],
        status: 'Screening in Progress',
        createdAt: '2026-02-07T10:00:00Z',
        applicationCount: 214,
        strongCount: 0,
        shortlistedCount: 12,
        daysOpen: 20,
    },
    {
        id: 'jd2',
        title: 'Product Manager – Fintech',
        department: 'Product',
        location: 'Bangalore',
        experienceMin: 5,
        experienceMax: 10,
        description: `We're seeking a Product Manager to own the roadmap for our core payment and lending products. You'll translate complex regulatory and user needs into clear PRDs, prioritise a backlog of high-impact features, and drive cross-functional execution with Engineering, Design, Risk, and Compliance.\n\nSuccess here requires deep fintech domain knowledge, a data-first mindset, and the ability to influence without authority across a matrixed organisation.`,
        mustHaveSkills: ['Product Strategy', 'User Research', 'SQL', 'Fintech Experience'],
        niceToHave: ['MBA', 'Analytics', 'Agile', 'Payments Domain'],
        status: 'Live – Accepting Applications',
        createdAt: '2026-02-10T09:00:00Z',
        applicationCount: 634,
        strongCount: 0,
        shortlistedCount: 0,
        daysOpen: 17,
    },
    {
        id: 'jd3',
        title: 'Backend Lead (Node.js)',
        department: 'Engineering',
        location: 'Remote',
        experienceMin: 7,
        experienceMax: 12,
        description: `We need a Backend Lead to architect and own our distributed services layer powering millions of real-time transactions. You'll set technical direction for a team of 6, define API contracts, own reliability SLOs, and lead the migration from monolith to microservices.\n\nStrong candidates will have hands-on experience scaling Node.js services to 10k+ RPS, deep PostgreSQL and Redis expertise, and a track record of engineering leadership.`,
        mustHaveSkills: ['Node.js', 'PostgreSQL', 'Redis', 'System Design', 'Cloud Architecture'],
        niceToHave: ['Kubernetes', 'Go', 'Python', 'Microservices'],
        status: 'Offer Closed',
        createdAt: '2026-01-12T14:00:00Z',
        applicationCount: 143,
        strongCount: 0,
        shortlistedCount: 5,
        daysOpen: 38,
    },
    {
        id: 'jd4',
        title: 'Frontend Engineer (React)',
        department: 'Engineering',
        location: 'Mumbai',
        experienceMin: 3,
        experienceMax: 6,
        description: `We're hiring a Frontend Engineer to build beautiful, performant, and accessible UIs for our customer portal and merchant dashboard. You'll own component design, collaborate closely with Figma designs from our Design team, and write well-tested React code.\n\nThe ideal candidate cares deeply about user experience, writes clean TypeScript, and has strong opinions on component architecture and state management.`,
        mustHaveSkills: ['React', 'TypeScript', 'Tailwind CSS', 'Redux'],
        niceToHave: ['Next.js', 'Testing Library', 'Figma', 'Storybook'],
        status: 'Live – Accepting Applications',
        createdAt: '2026-02-25T11:30:00Z',
        applicationCount: 0,
        strongCount: 0,
        shortlistedCount: 0,
        daysOpen: 2,
    },
    {
        id: 'jd5',
        title: 'Data Analyst – Growth',
        department: 'Analytics',
        location: 'Hyderabad',
        experienceMin: 2,
        experienceMax: 5,
        description: `We're looking for a Data Analyst to partner with our Growth and Marketing teams, turning large datasets into actionable insights that drive acquisition, activation, and retention.\n\nYou'll build dashboards in Tableau, write complex SQL across our warehouse, design and analyse A/B experiments, and present findings to senior stakeholders in a clear, business-first narrative.`,
        mustHaveSkills: ['SQL', 'Python', 'Tableau', 'Statistics'],
        niceToHave: ['dbt', 'BigQuery', 'Looker', 'A/B Testing'],
        status: 'Interview',
        createdAt: '2026-01-28T10:00:00Z',
        applicationCount: 96,
        strongCount: 0,
        shortlistedCount: 6,
        daysOpen: 30,
    },
    {
        id: 'jd6',
        title: 'DevOps Engineer',
        department: 'Infrastructure',
        location: 'Remote',
        experienceMin: 4,
        experienceMax: 8,
        description: `We're hiring a DevOps Engineer to elevate our infrastructure reliability and developer productivity. You'll own CI/CD pipelines, manage our Kubernetes clusters on AWS, set up end-to-end observability with Prometheus and Grafana, and drive SRE best practices across engineering.\n\nIdeal candidates have automated away toil, built zero-downtime deployment pipelines, and have strong IaC experience with Terraform.`,
        mustHaveSkills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD'],
        niceToHave: ['Go', 'Prometheus', 'Grafana', 'Helm'],
        status: 'Offer Extended',
        createdAt: '2026-01-20T09:00:00Z',
        applicationCount: 61,
        strongCount: 0,
        shortlistedCount: 3,
        daysOpen: 37,
    },
];
